### ISSUE TITLE
Empty lightning_args

### ISSUE THREAD

**Issue by aengusl** [biomedia-mira/deepscm#7]
Hi, I've failed to run your code and I am getting this message

AttributeError: 'Namespace' object has no attribute 'default_root_dir

It seems that the lighning_args is the issue here. Also here is the command that I have run:

python -m deepscm.experiments.morphomnist.trainer -e SVIExperiment -m IndependentVISEM --data_dir ~/Desktop/Projects/Benchmarking/deepscm/dataset --default_root_dir ~/Desktop/Projects/Benchmarking/checkpoints1 --decoder_type fixed_var --gpus=1

**Comment by aengusl** [comment]
Issue resolved:

Pytorch lightning updates changed a few things that interfered with the running of this code. I ran 

pip install pytorch-lightning==1.1.2

and everything fixed

**Comment by dccastro** [comment]
Hi @aengusl, thanks for trying out our code! We haven't had time to keep this codebase up-to-date, so issues like this may pop up because of newer package versions. Glad you managed to resolve it!
